#!/bin/bash
[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C
Peter Sunday@Gokada-L00578 MINGW64 ~/alx-system_engineering-devops/0x02-shell_redirections (main)
[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C cd ls
[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C $ cd ls
[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[

[A[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C
$ ls
[D[D[D[D[w